SELECT * FROM V$DATABASE;

SELECT * FROM DBA_USERS;

ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;

CREATE USER SISTEMA IDENTIFIED BY "@abc123@"
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON USERS;

GRANT CREATE SESSION TO SISTEMA;
GRANT CREATE TABLE TO SISTEMA;
GRANT CREATE VIEW TO SISTEMA;
GRANT CREATE PROCEDURE TO SISTEMA;
GRANT CREATE TRIGGER TO SISTEMA;
GRANT CREATE SEQUENCE TO SISTEMA;
GRANT CREATE JOB TO SISTEMA;


-- Código para crear usuario con un TableSpace
CREATE TABLESPACE TBSLABORATORIO
DATAFILE 'tbslaboratorio.dbf'
SIZE 200M;

CREATE USER USER_ORACLE IDENTIFIED BY "73829932"
DEFAULT TABLESPACE TBSLABORATORIO
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON TBSLABORATORIO;

GRANT CREATE SESSION TO USER_ORACLE;
GRANT CREATE TABLE TO USER_ORACLE;
GRANT CREATE VIEW TO USER_ORACLE;
GRANT CREATE PROCEDURE TO USER_ORACLE;
GRANT CREATE TRIGGER TO USER_ORACLE;
GRANT CREATE SEQUENCE TO USER_ORACLE;
GRANT CREATE JOB TO USER_ORACLE;
GRANT UNLIMITED TABLESPACE TO USER_ORACLE;


-- Linea de código para NestJs, al principio del proyecto
npm install --save @nestjs/typeorm typeorm oracledb